### PR TITLE
make change so that component works with provided sample data

### PR DESCRIPTION
**Pull request by kirkins**
I'm not sure if this project needs to change the sample data or the component. 

I changed the data that OpenWeatherMap.js looks for to work with the sample data.

Let me know if the mistake was actually in the sample data, in which case these changes probably break working with actual API data.

Cheers,
Phil

### CODE REVIEW

**Comment by kirkins** [comment]
Ok I realized the component was exactly right for working with Open Weather API. 

It seemed it was only the sample data that was an issue. So I reverted the change to component and just replaced the sample data file.

**Comment by mattiaerre** [comment]
Hi @kirkins thanks for showing your interest in this component.

Unfortunately, the PR you are proposing is breaking the tests (try to run `npm t`) although you are right, the example doesn't work.

The sample data at the moment is an object that w/ a `weather` property and that object is the data structure used by the react component.

What about:

1. revert back `data/current-weather-data-sample.json`

2. change https://github.com/mattiaerre/react-open-weather-map/blob/master/example.js#L15 into something like: `const props = { data: sample.weather }`

3. run `npm t`

4. run `npm run example`

everything should work (both the tests and the example)

if you can try and update your PR I will be more than happy to merge it.

thank you very much,

-Mattia

// this will fix #3

**Comment by kirkins** [comment]
I updated the change to match your suggestion. Also thanks for making this. I need to make something similar and this will be a great starting point.

Cheers,
Phil

**Comment by mattiaerre** [comment]
LGTM 👍  thanks @kirkins 

that's cool; let me know if there is anything I can do in order to help you w/ your next task 😊  

also I'll let you know when I re-publish this component to `npm`

**Comment by mattiaerre** [comment]
v2.1.1 has been published to npm

- https://github.com/mattiaerre/react-open-weather-map/releases/tag/v2.1.1

- https://www.npmjs.com/package/react-open-weather-map

// cc @kirkins

**Pull request merged**
